

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app  # Hot reload and persistence in dev
      - ./instance:/app/instance # persist SQLite DB in dev
    restart: always