name: Deploy & Test

on:
  push:
    branches:
      - main
      - final-exam

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Run containers in background
        run: docker compose up -d

      - name: Wait for app to be ready
        run: sleep 5  # optional: wait for app init

      - name: Run tests
        run: docker compose run --rm web pytest tests/ -v

      - name: Tear down
        run: docker compose down --volumes
